### ISSUE TITLE
Modificacion de perfil - Pasajeros

### ISSUE THREAD

**Issue by luciaCP** [llevame/application-server#10]
1. Datos personales
        - Post (no disponible pues todos los campos son obigatorios inicialmente(?))
        - Put: Permitir modificar email (apellido, nombre se tomaran de la tarjeta?)

2. Datos de tarjeta
        - Put: Permitir modificar los datos de la tarjeta

3. Preferencias
        - Post (no disponible pues todos los campos tendran a lo sumo un valor por defecto(?))
        - Put: Permitir modificar las preferencias del pasajero

**Comment by nicolasgalvarez91** [comment]
Por ahora ya deje los endpoints creados, faltaria hacer la conexion con la base de datos y el otro servidor
